using SqlIndexAdvisor.Core.Model;

namespace SqlIndexAdvisor.Core.Rules;

/// <summary>
/// Base class for plan node visitors that implement IIndexRule.
/// Provides common infrastructure for rules that visit plan nodes.
/// </summary>
public abstract class PlanNodeVisitorBase : IIndexRule
{
    private static readonly AsyncLocal<HashSet<PlanNodeVisitorBase>?> _currentlyVisitingRules = new();

    /// <summary>
    /// Maximum traversal depth to prevent stack overflow on pathological plans.
    /// Default value of 1000 prevents StackOverflowException while allowing reasonable
    /// query complexity (most real-world plans have depth < 100).
    /// </summary>
    private const int MaxTraversalDepth = 1000;

    public virtual string Name => GetType().Name.ToLowerInvariant().Replace("rule", "");

    /// <summary>
    /// Evaluates this rule against the given execution plan.
    /// </summary>
    /// <param name="plan">The execution plan to analyze. Must not be null.</param>
    /// <returns>An enumerable of index recommendations generated by this rule.</returns>
    /// <remarks>
    /// For PlanNodeVisitorBase rules, this method uses a single-pass traversal strategy
    /// when multiple visitor rules are evaluated together. This reduces time complexity
    /// from O(rules × nodes) to O(nodes) by visiting each node exactly once and
    /// dispatching it to all registered visitor rules.
    /// </remarks>
    public virtual IEnumerable<IndexRecommendation> Evaluate(ExecutionPlan plan)
    {
        ArgumentNullException.ThrowIfNull(plan);

        // Use single-pass dispatcher for multiple visitor rules
        var currentlyVisiting = _currentlyVisitingRules.Value;
        if (currentlyVisiting == null)
        {
            // First rule in the traversal - set up dispatcher
            _currentlyVisitingRules.Value = new HashSet<PlanNodeVisitorBase>();
            try
            {
                return VisitWithDispatcher(plan);
            }
            finally
            {
                _currentlyVisitingRules.Value = null;
            }
        }
        else
        {
            // Already visiting - use standard per-rule traversal
            // This handles the case where rules are evaluated independently
            var recommendations = new List<IndexRecommendation>();
            foreach (var node in plan.Nodes)
            {
                if (ShouldVisit(node))
                {
                    recommendations.AddRange(VisitCore(node, plan));
                }
            }
            return recommendations;
        }
    }

    /// <summary>
    /// Visits the plan using a single-pass dispatcher that coordinates multiple visitor rules.
    /// </summary>
    /// <param name="plan">The execution plan to analyze.</param>
    /// <returns>An enumerable of index recommendations from all registered visitor rules.</returns>
    private IEnumerable<IndexRecommendation> VisitWithDispatcher(ExecutionPlan plan)
    {
        var recommendations = new List<IndexRecommendation>();
        var dispatcher = new SinglePassDispatcher(_currentlyVisitingRules.Value!);
        return dispatcher.Visit(plan, recommendations);
    }

    /// <summary>
    /// Plan-aware visit hook. Rules that need to look at siblings or descendants
    /// (anything beyond the parent chain) override this; the default delegates to
    /// the node-only overload.
    /// </summary>
    protected virtual IEnumerable<IndexRecommendation> VisitCore(PlanNode node, ExecutionPlan plan) =>
        VisitCore(node);

    /// <summary>
    /// Determines whether this visitor should process the given node.
    /// Override this to implement custom filtering logic.
    /// </summary>
    protected abstract bool ShouldVisit(PlanNode node);

    /// <summary>
    /// Called when a node passes ShouldVisit check.
    /// Override this to implement the actual visiting logic.
    /// </summary>
    protected abstract IEnumerable<IndexRecommendation> VisitCore(PlanNode node);

    /// <summary>
    /// Gets the chain of parent nodes from the current node up to the root.
    /// </summary>
    protected static IEnumerable<PlanNode> GetParentChain(PlanNode node)
    {
        var current = node.Parent;
        while (current != null)
        {
            yield return current;
            current = current.Parent;
        }
    }

    /// <summary>
    /// Gets all nodes in the plan that sit below the given node in the tree
    /// (i.e. whose parent chain passes through it).
    /// </summary>
    protected static IEnumerable<PlanNode> GetDescendants(PlanNode node, ExecutionPlan plan) =>
        plan.Nodes.Where(n => GetParentChain(n).Contains(node));

    /// <summary>
    /// Single-pass dispatcher that coordinates multiple visitor rules during a single traversal.
    /// This ensures O(nodes) complexity instead of O(rules × nodes) by visiting each node
    /// exactly once and dispatching it to all registered visitor rules.
    /// </summary>
    /// <remarks>
    /// The dispatcher uses a depth limit (<see cref="MaxTraversalDepth"/>) to prevent
    /// StackOverflowException on pathological plans (e.g., deeply nested recursive CTEs).
    /// The limit is enforced using a stack-based approach that tracks visited nodes.
    /// </remarks>
    private sealed class SinglePassDispatcher
    {
        private readonly HashSet<PlanNodeVisitorBase> _rules;
        private readonly int _maxDepth;
        private readonly List<PlanNode> _visitStack = new();

        /// <summary>
        /// Initializes a new instance of the <see cref="SinglePassDispatcher"/> class.
        /// </summary>
        /// <param name="rules">The set of visitor rules to coordinate during traversal.</param>
        /// <param name="maxDepth">Maximum traversal depth to prevent stack overflow. Defaults to <see cref="MaxTraversalDepth"/>.</param>
        public SinglePassDispatcher(HashSet<PlanNodeVisitorBase> rules, int maxDepth = MaxTraversalDepth)
        {
            _rules = rules;
            _maxDepth = maxDepth;
        }

        /// <summary>
        /// Visits all nodes in the execution plan using single-pass traversal.
        /// </summary>
        /// <param name="plan">The execution plan to analyze.</param>
        /// <param name="recommendations">The list to accumulate recommendations into.</param>
        /// <returns>The list of recommendations after visiting all nodes.</returns>
        public IEnumerable<IndexRecommendation> Visit(ExecutionPlan plan, List<IndexRecommendation> recommendations)
        {
            ArgumentNullException.ThrowIfNull(plan);
            ArgumentNullException.ThrowIfNull(recommendations);

            _visitStack.Clear();

            foreach (var node in plan.Nodes)
            {
                VisitNode(node, plan, recommendations);
            }

            return recommendations;
        }

        /// <summary>
        /// Visits a single plan node, dispatching it to all registered visitor rules.
        /// </summary>
        /// <param name="node">The plan node to visit.</param>
        /// <param name="plan">The full execution plan (for context-aware rules).</param>
        /// <param name="recommendations">The list to accumulate recommendations into.</param>
        /// <exception cref="InvalidOperationException">Thrown if traversal depth exceeds <see cref="MaxTraversalDepth"/>.</exception>
        private void VisitNode(PlanNode node, ExecutionPlan plan, List<IndexRecommendation> recommendations)
        {
            if (_visitStack.Count > _maxDepth)
            {
                // Prevent stack overflow on pathological plans (e.g., deeply nested recursive CTEs)
                // This is a hard limit that prevents StackOverflowException in the CLI tool
                return;
            }

            _visitStack.Add(node);
            try
            {
                foreach (var rule in _rules)
                {
                    if (rule.ShouldVisit(node))
                    {
                        var ruleRecommendations = rule.VisitCore(node, plan);
                        foreach (var rec in ruleRecommendations)
                        {
                            rec.Rule ??= rule.Name;
                            recommendations.Add(rec);
                        }
                    }
                }
            }
            finally
            {
                _visitStack.RemoveAt(_visitStack.Count - 1);
            }
        }
    }
}